# Generated by Django 3.1.7 on 2021-03-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_stockhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
